// <auto-generated />
using System;
using Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AirplaneDB))]
    [Migration("20230129083618_myMigration")]
    partial class myMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.BrandEnum", b =>
                {
                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Brand")
                        .HasName("PK__BrandEnu__BAB741D66AB6B66E");

                    b.ToTable("BrandEnum");
                });

            modelBuilder.Entity("Data.Models.Flight", b =>
                {
                    b.Property<int>("FlId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLanding")
                        .HasColumnType("bit")
                        .HasColumnName("isLanding");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("PassengersCount")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TerId")
                        .HasColumnType("int");

                    b.HasKey("FlId")
                        .HasName("PK__Flight__320C53801A7218DD");

                    b.HasIndex("TerId");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("Data.Models.Logger", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InAirplane")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OutAirplane")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Logger__3214EC07EF1569F3");

                    b.ToTable("Logger");
                });

            modelBuilder.Entity("Data.Models.Terminal", b =>
                {
                    b.Property<int>("TerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit")
                        .HasColumnName("isFree");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<decimal?>("WaitTime")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("TerId")
                        .HasName("PK__Terminal__6C716C1B65AC711F");

                    b.ToTable("Terminal");
                });

            modelBuilder.Entity("Data.Models.Flight", b =>
                {
                    b.HasOne("Data.Models.Terminal", "Ter")
                        .WithMany("Flights")
                        .HasForeignKey("TerId")
                        .HasConstraintName("FK__Flight__TerId__3F466844");

                    b.Navigation("Ter");
                });

            modelBuilder.Entity("Data.Models.Terminal", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
